### ISSUE TITLE
onAfterLoad prop is not passed to LC_API correctly

### ISSUE THREAD

**Issue by mihkeleidast** [livechat/react-livechat#10]
currently the prop function is called directly, not bound like other methods.

`window.LC_API.on_after_load = this.props.onAfterLoad();`
should be
`window.LC_API.on_after_load = this.props.onAfterLoad.bind(this);`
or just
`window.LC_API.on_after_load = this.props.onAfterLoad`.

**Comment by tomekvenits** [comment]
Hi,

Thanks for pointing that out ;)

In module version: `1.0.25` is fixed that and its should work fine :)

**Comment by mihkeleidast** [comment]
Thank you for the quick fix!
