### ISSUE TITLE
LC_Invite is not defined 

### ISSUE THREAD

**Issue by GerjoGreenwaldMM** [livechat/react-livechat#11]
Hi, 
I have an issue where the component throws an error "LC_Invite is not defined". I use code below. I cut a bit in the code to hide the chatwindow on mobile:

`onChatLoaded(ref) {
    this.livechat = ref;
    if (
      matchMedia("only screen and (max-width: 768px)").matches
    ) {
      this.livechat.hide_chat_window();
    }
  }`

And later on i pass this to the component like usual:

`<LiveChatInc
        license={livechat.license} 
        onChatLoaded={this.onChatLoaded}
      />`

Now, if i look at my rollbar error logging i see it throws error on LC_Invite, please see screenshots. 
<img width="831" alt="screen shot 2018-06-07 at 15 08 08" src="https://user-images.githubusercontent.com/40030735/41103001-69e6d5ae-6a68-11e8-89e1-16d61c4a993e.png">
<img width="1271" alt="screen shot 2018-06-07 at 15 03 08" src="https://user-images.githubusercontent.com/40030735/41103028-75d17fae-6a68-11e8-9e13-a224327f8b39.png">

Code it's refering to:
<img width="665" alt="screen shot 2018-06-07 at 15 39 29" src="https://user-images.githubusercontent.com/40030735/41103278-0a43f1da-6a69-11e8-89b8-8b111743b379.png">

It seems like not the whole library is loaded on this point in time, but how should this be done instead for the hidden mobile version? Or is this a bug?

**Comment by GerjoGreenwaldMM** [comment]
I just found the possible solution to this here:
https://github.com/livechat/react-livechat/issues/7

For clarification, perhaps this can be added to the documentation?

**Comment by tomekvenits** [comment]
Hi,
the problem is that LC_Invite is still being loaded when onChatLoaded is called.
Here is what you can do to ensure that LC_Invite will be loaded when you call your methods:
```js
onChatLoaded = (ref) => {
 this.livechat = ref;
 ref.on_after_load = function ()  {
    if(matchMedia...)
    else this.livechat.hide_chat_window();
  }		
}
```

Please let me know if that worked for you ;)

**Comment by lacroixdavid1** [comment]
Thx @venits
