### ISSUE TITLE
Error: Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by mikeaustin** [livechat/react-livechat#12]
This is solvable by excluding the node_modules path, but it can also be solved by using preset "env", which is now the standard. If I have time I can see if it's easy and create a pull request.

./node_modules/react-livechat/LiveChat.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory 

node v6.11.4
preact v8.2.7
webpack v3.10

**Comment by tomekvenits** [comment]
Hi,
issue solved in version `1.0.26`.

Here is our `.babelrc` file.

```js
{
  "presets": [
    "stage-1",
    "stage-0",
    "react",
    "es2015",
    [
      "latest", {
      "es2015": {
        "modules": false
      }
    }
    ]
  ],
  "plugins": ["transform-class-properties", "transform-runtime"]
}
```

Now it should work fine ;)
