### ISSUE TITLE
onChatLoaded should not be passed a string when the expectation is the API object

### ISSUE THREAD

**Issue by meta-meta** [livechat/react-livechat#14]
Given this line:
https://github.com/livechat/react-livechat/blob/master/LiveChat/LiveChat.js#L20

This usage is unsafe. 
```
<LiveChat 
  onChatLoaded={ ref => { ref.chat_window_hidden() } }
  license={your_license_id} 
/>
```

At the very least, this should be documented but I recommend adding a callback `onErrorLoading` to handle errors.

**Comment by tomekvenits** [comment]
Hi,
yep you are right. In version `1.0.26` the problem is gone.
Now this line is:
```js
chatNotLoaded() {
    if (typeof this.props.onErrorLoading === 'function') {
      this.props.onErrorLoading();
    }
  }
```
