### ISSUE TITLE
Chat messages gets hidden when opening the keyboard on app

### ISSUE THREAD

**Issue by ankitbhattsdd** [livechat/react-livechat#15]
When i open the keyboard then the previous app gets hidden instead of floating upwards. 

 <KeyboardAwareScrollView style={{ backgroundColor: 'white' }} keyboardShouldPersistTaps={'always'}>
                    < LiveChat bubbleColor = '#E18C50'
                    license={} bubbleLeft={w * .75} onLoaded={ref => this.livechat = ref} style={{ height: h * .5 }} 
                    bubbleTop={h * .8} bottomOffset={h * .5} /> 
            </KeyboardAwareScrollView>

![screenshot_1533632254](https://user-images.githubusercontent.com/32154346/43839563-0b044710-9b3c-11e8-87fc-b6c4ac41969c.png)
![screenshot_1533632441](https://user-images.githubusercontent.com/32154346/43839570-116aec4e-9b3c-11e8-97e0-71ace87b3f05.png)

**Comment by ankitbhattsdd** [comment]
Any updates regarding this?

**Comment by tomekvenits** [comment]
Hi, isn't this issue related to https://github.com/livechat/react-native-livechat rather than react-livechat? I assumed this since you are using `<KeyboardAwareScrollView/>`. Am I right?

**Comment by brijeshpant83** [comment]
I had a same issue, plugin unable to open keyboard and latest message is not showing above keyboard which is common chat behaviour.

**Comment by quarties** [comment]
@brijeshpant83 please recreate the issue in https://github.com/livechat/react-native-livechat repository - it's separated project not related to this one.
