### ISSUE TITLE
Method for pre-filling Pre-chat survey not supported.

### ISSUE THREAD

**Issue by akkikumar72** [livechat/react-livechat#16]
Actually, we can prefill Pre-chat survey by using 

`window.__lc.visitor = { name: 'Aksxxx', email: 'aks.xxx@gmail.com' };`

But by using react-livechat component it's not possible. 

Will be great if we can add its support.

**Comment by quarties** [comment]
Hello @akkikumar72 

That's brand idea and it's developed on this pull request: https://github.com/livechat/react-livechat/pull/17

I'll let you know when it will be merged to master and published at npm

**Comment by akkikumar72** [comment]
Awesome, that's really fast

**Comment by quarties** [comment]
@akkikumar72 the pull request is already merged, so in a few moments it should be available at npm repository

meanwhile, I'm closing this issue - once again thanks :-)
