### ISSUE TITLE
Can't hide visibility of Chat Window once its loaded in page

### ISSUE THREAD

**Issue by akkikumar72** [livechat/react-livechat#18]
Once the LiveChat chat window is loaded on the page.
Can't we hide it from the page? Do we explicitly have to load the page again?

**Comment by tomekvenits** [comment]
Hi, If you want to hide chat window, you can use following code:

```js
onChatLoaded = (ref) => {
 ref.on_after_load = function ()  {
    ref.hide_chat_window();
  }		
}

<LiveChat 
  onChatLoaded={ ref => this.livechat = ref }
  license={your_license_id} 
/>
```

So basically you have to wait for our widget to load and then hide it.
