### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by smasinde** [livechat/react-livechat#19]
I'm using GatsbyJS. 
With the basic setup, it works in `gatsby develop` but running `gatsby build` yield an error. Changing the import to require and conditionally importing it is bring back "Expected string but got object" error. Any advice?

**Comment by mwisner** [comment]
I'm not sure if it works the same in GatsbyJS, but we just ran into this issue with nextjs. 

The `componentDidMount` hook only runs on the client... So what we did was create a state value `initChat` which is used to conditionally render the liveChat component. We set the default to false and then use the componentDidMount method to set it to true. (This ensures the <LiveChat /> component will only be rendered on the client.

**Comment by develanet** [comment]
> I'm not sure if it works the same in GatsbyJS, but we just ran into this issue with nextjs.
> 
> The `componentDidMount` hook only runs on the client... So what we did was create a state value `initChat` which is used to conditionally render the liveChat component. We set the default to false and then use the componentDidMount method to set it to true. (This ensures the component will only be rendered on the client.

Suggestion from @mwisner worked out on my Gatsby site:

```
class Header extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      initChat: false
    };
  }

  componentDidMount() {
    this.setState({
      initChat: true
    });
  }
  render() {
    return (
     <>
        {this.state.initChat === true && <LiveChat license={XXXXXX} /> }
     </>
    );
  }
}
```
Thanks!
