### ISSUE TITLE
Failed to minify the code from this file:   ./node_modules/react-livechat/LiveChat/LiveChat.js:4

### ISSUE THREAD

**Issue by RezikoChkadua** [livechat/react-livechat#2]
i'm using create react app and having this error when trying to build project

Failed to compile.

Failed to minify the code from this file:

    ./node_modules/react-livechat/LiveChat/LiveChat.js:4

**Comment by tomekvenits** [comment]
Hi, please check new version: 1.0.20
It should work fine ;)
