### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by brightonmike** [livechat/react-livechat#20]
Hi.

We are using LiveChat on a clients website. Unfortunately, the performance hit is quite significant. Livechat causes numerous red flags to be raised by Chrome developer tools - examples are below.

These performance issues are causing the site to not function as smoothly as we'd like. I am not sure what the solution is exactly - but I think it's worth looking into these problems and trying to improve the performance of the code base.

<img width="271" alt="screen shot 2018-09-20 at 09 17 48" src="https://user-images.githubusercontent.com/2071150/45805304-5622ef80-bcb6-11e8-809c-297ae71350a7.png">

**Comment by akkikumar72** [comment]
Following. 
Facing the same issue + they are making an XHR call every sec 👎

**Comment by tomekvenits** [comment]
It is problem with LiveChat itself rather with this library. I will inform our team about this problem 👍
