### ISSUE TITLE
Reassigning params in functions is not a good practice

### ISSUE THREAD

**Issue by mxdi9i7** [livechat/react-livechat#21]
In the documentation to allow chat to get access to API methods, the sample code demostrates
```
onChatLoaded = (ref) => {
 ref.on_after_load = function ()  {
    //here you can use any method you want!
  }		
}
```
This is not a good practice according to ES standards, you should not reassign ref within the function scope because ref is considered a constant that's passed in as a parameter. please update the documentation to reduce the confusion.

**Comment by tomekvenits** [comment]
It this case `ref` is not refered as DOM element but rather reference to LiveChat object.
