### ISSUE TITLE
Ticket Form not opening in Live Chat even when Agents are not Accepting Chats

### ISSUE THREAD

**Issue by Ankleshwar** [livechat/react-livechat#25]
We have integrated your Live Chat SDK with one of our mobile apps build on React Native. We notice that user is unable to send a chat to agent, when agents are logged off from the Live Chat Web Panel. In this case, user should ideally receive a Ticket Form but unfortunately that is also not happening. We tried to contact with your customer care and had a word with Lukasz who informed us that we have to make sure that all agents should not ACCEPT CHATS. We tried that also but couldn’t get through. Hence, reporting this as an issue here as suggested by your team. Looking forward for an early response.

**Comment by rajesh-strategy** [comment]
any updates on this?

**Comment by tomekvenits** [comment]
Hi,

ideally when you work with React Native you should use this library:
https://github.com/livechat/react-native-livechat

It gives much more possibilities ;) Our react-native library uses:
https://developers.livechatinc.com/docs/visitor-sdk

Visitor SDK allows you to create your own chat and ticket system and control every aspect in your application. Probably you will be interested in methods such as:
https://developers.livechatinc.com/docs/visitor-sdk/#sendticketform

I hope it will help you ;)

**Comment by AnkleshwarDwivedi** [comment]
Hi,
We use your  visitor-sdk in new project but its not working, it shows this error 
   Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `@livechat/mitt` from file `/Documents/chatApp/node_modules/@livechat/livechat-visitor-sdk/dist/index.cjs.js`, the package `/Documents/chatApp/node_modules/@livechat/mitt/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Documents/chatApp/node_modules/@livechat/mitt/dist/livechat-mitt.native.js`. Indeed, none of these files exist:
We remove node_module and reinstall it but it show same error. Currently am using 
node: v10.11.0
npm: v6.4.1
react-native-cli: 2.0.1
macOS: 10.13.6

**Comment by ghost** [comment]
Same problem. **Any solution**????

**Comment by tomekvenits** [comment]
Problem should be gone by now. Modules where repaired.

**Comment by ghost** [comment]
Still not working, having the same error while trying to implement chat using your sdk
