### ISSUE TITLE
Can't hide visibility of Chat Window BEFORE its loaded in page

### ISSUE THREAD

**Issue by olegtabu** [livechat/react-livechat#27]
There is similiar solved issue [Can't hide visibility of Chat Window once its loaded in page #18] but the solution is to use on_after_load, but if we do not want to show chat window by default, this solution is not perfect because of short blinking (window apear for a moment and than disapear). If we using on_before_load, chat window does not disapear (why?). Best if it will be some property, for example "hide_on_startup", which do the job. Or maybe you know beter/simpler solution.

**Comment by tomekvenits** [comment]
Hi,
that is true you can't hide chat before its loaded because it is not loaded.

Best option if you want to for example: "Load chat when user clicks the button", will be loading LiveChat's script on `onClick` listener.
