### ISSUE TITLE
LiveChat makes ping even after unmounting

### ISSUE THREAD

**Issue by vadymdykyi90** [livechat/react-livechat#29]
Hi. I have faced with a problem.
On my site I have a lot of routes: site.com/home, site.com/game, site.com/about and so on.
I want to render LiveChat wherever but not on site.com/game.
I tried to use conditional render in my root component like this:

`{showChat && (<LiveChatWrapper license={1234} />)}`

In LiveChatWrapper component I am hiding chat window in componentWillUnmount():

```
componentWillUnmount() {
  if (this.chatRef) {
    this.chatRef.close_chat();
    this.chatRef.hide_chat_window();
  }
}
```

This works. But even if the chat is hidden I see a lot of requests to https://secure.livechatinc.com/licence/1234/v2/ping.
I want to be sure that if LiveChat is unmounted there is no network activity.

How can I achieve this?

**Comment by tomekvenits** [comment]
Hi,
yes It can be true.

You have to destroy `window.LC_API` also.
There should be method available like `window.LC_API.destroy()` or you can simply do `window.LC_API = null`;

**Comment by vadymdykyi90** [comment]
I tried `window.LC_API = null` (`window.LC_API.destroy()` doesn't work: destroy is not a function).
Nothing is changed. I still have ping requests

**Comment by tomekvenits** [comment]
Hmm probably the only way will be to find URL of websocket. I thould be something like this:
`wss://api.livechatinc.com/v3.0/agent/rtm/ws` and then close this connection.

**Comment by vadymdykyi90** [comment]
No socket connections at all.
Ping is sending by HTTP method GET from initiator tracking.js

**Comment by tomekvenits** [comment]
Hmm it looks like once the LiveChat script is loaded on page the times is set.
You can contact **support@livechatinc.com**  since this problem is related to our global script that this library only loads.

**Comment by vadymdykyi90** [comment]
So, I have got the answer from support:

> Hello
> I consulted your issue with our technical team and the developers
> Unfortunately there are currently no methods that would allow stopping the pings after the LiveChat code has been executed on the page for React/LC_API
> We also thought about inserting a 'destroy' that would allow you to kill the pings but that also proven to not be possible though the pings get automatically shut down after 30 minutes without activity on page/application

I am definitely saddened...
