### ISSUE TITLE
I desperately need the new params prop feature I see in LiveChat.js src

### ISSUE THREAD

**Issue by clayembry** [livechat/react-livechat#3]
Hi. I desperately need the new "params" prop feature I see in the LiveChat.js src. But the latest 1.0.19 release available via npm does not have it. When can we expect the next release?

Sorry to raise this as an Issue, but that's what livechat support told me to do.

**Comment by tomekvenits** [comment]
Hi, thanks for pointing that out :)

Please check version: 1.0.21
I added 'params' feature there.
