### ISSUE TITLE
Can't resolve 'react' (create-react-app)

### ISSUE THREAD

**Issue by guix77** [livechat/react-livechat#34]
Hi,

I get

`Module not found: Can't resolve 'react' in ...`

React 16.4.2 with create-react-app 2

Of course I'm importing React...

`import React from 'react'`

Any idea?

**Comment by tomekvenits** [comment]
Hmm can you send me the wole `js` code in your file? I mean like `index.js` or something where you are using our module.

**Comment by guix77** [comment]
On a freshly created CRA, I don't get this issue.

I'm getting

`https://secure.livechatinc.com/licence/123456/v2/get_dynamic_config.js?t=123456&referrer=&url=http%3A%2F%2Flocalhost%3A3000%2F&params=&jsonp=__lc_data_123456&groups=0`

but it's another story :)

**Comment by guix77** [comment]
It's not in index.js, it's in a component imported in App.js. I'll try to import it somewhere else and send you the file if it still does not work. Thanks :)

**Comment by guix77** [comment]
My bad, I'm so stupid, I added the module in the wrong directory. It should be Saturday already, for my brain. Lol
