### ISSUE TITLE
User infos not updated after visitor prop changed

### ISSUE THREAD

**Issue by IcanDivideBy0** [livechat/react-livechat#35]
User infos should be updated (in livechat admin) when the visitor prop is changed.

**Comment by tomekvenits** [comment]
Hi,
you can try overwrite global values that LiveChat uses.
```js
   window.__lc.params = this.props.params;
   window.__lc.visitor = this.props.visitor;
```

That are only set when LiveChat loads so I am not sure if they will automatically update, but they should :)

**Comment by IcanDivideBy0** [comment]
Thanks for the workaround, i'll try that.
But still I'd prefer the value to be auto sync'ed with the prop

**Comment by walaszczykm** [comment]
Hello @IcanDivideBy0 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The Hooks API is one part of the new React package: [@livechat/widget-react](http://npm.im/@livechat/widget-react).

In the new implementation, all props for the main component are synced with Chat Widget 🙂
