### ISSUE TITLE
Chat does not display before agent replies

### ISSUE THREAD

**Issue by Steven-S-Francis** [livechat/react-livechat#39]
Hi,

I have been facing this issue for sometime, I am using livechat default send implementation.

When a visitor types in a message and sends it, it doesn't appear until the agent replies (either if it automatic assign or manual assign)

if no agents online, then the visitor can't know if the messages are sent to the chat or not.

Also, I have noticed that when I implemented the sendPrechatForm, it automatic starts the chat, and that causes the messages to be re-rendered multiple times till I go back and forth.

Screenshot showing that the welcome message show'd before the visitor's message and also causing the duplication to happen
![image](https://user-images.githubusercontent.com/30292209/60774464-7a03d480-a114-11e9-95af-cdb43059ce70.png)

![image](https://user-images.githubusercontent.com/30292209/60774415-04980400-a114-11e9-960c-12e940b9bb59.png)

**Comment by walaszczykm** [comment]
Hello 👋 

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters).

We didn't observe such issue on the new version but you can try it your self and tell what you think about it 🙂
