### ISSUE TITLE
Wrong directory structure published on npm

### ISSUE THREAD

**Issue by MartynasSapoka** [livechat/react-livechat#4]
In the package published on npm (Version 1.0.21) `LiveChat.js` is placed in the root directory but
`index.js` imports `LiveChat.js` from a subdirectory `LiveChat` - `require('./LiveChat/LiveChat')`.

Please fix 🙂

**Comment by tomekvenits** [comment]
Fixed. Thanks for pointing that out ;)

**Comment by MartynasSapoka** [comment]
Wonderful! Thanks for a quick fix 🙂
