### ISSUE TITLE
How do I integrate this in Angular 7?

### ISSUE THREAD

**Issue by Shashi-GS** [livechat/react-livechat#40]
Please help in integrating this library with Angular 7?

**Comment by piotros** [comment]
Use component dedicated for Angular applications: https://github.com/livechat/angular-livechat

**Comment by walaszczykm** [comment]
Hello @Shashi-GS  👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The dedicated Angular package is part of this project: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular)
