### ISSUE TITLE
Disable name and email on chat window

### ISSUE THREAD

**Issue by arkeds** [livechat/react-livechat#41]
Is there a way to disable name and email text field. So the 2 fields won't be editable by the user because the visitor name and email is already passed as props?

![Screenshot from 2019-08-06 17-32-56](https://user-images.githubusercontent.com/11252974/62529086-8cd30b80-b870-11e9-9e26-af96a00c47d6.png)

**Comment by walaszczykm** [comment]
Hello 👋 

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters).

Although nor this nor the new packages are meant to alter the UI layer of the Chat Widget, they only provide a programming interface for interacting with it.
