### ISSUE TITLE
componentWillMount usage is deprecated

### ISSUE THREAD

**Issue by emirotin** [livechat/react-livechat#42]
![](https://api.monosnap.com/file/download?id=Azh2wg6pr2eLeOsTuCoPem60t7oaKZ)

**Comment by walaszczykm** [comment]
Hello @emirotin 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The Hooks API is one part of the new React package: [@livechat/widget-react](http://npm.im/@livechat/widget-react).

In new implementation the class components and React lifecycle methods are no longer used instead we use function components and Hooks which will resolve all deprecation warnings related to them 😉
