### ISSUE TITLE
SameSite attribute warning in Chrome

### ISSUE THREAD

**Issue by ravinpatel** [livechat/react-livechat#45]
Hi,

I seem to get this warning in the console, What will I need to do to remove it? I suspect it may be a change on your side too.

Thanks in Advance

```A cookie associated with a cross-site resource at http://livechatinc.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.```

**Comment by walaszczykm** [comment]
Hello everyone 👋 

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters).

We didn't observe such issue with the new version. You can check it out your yourself and tell us what you think 🙂
