### ISSUE TITLE
Exception errors

### ISSUE THREAD

**Issue by amiadsoto** [livechat/react-livechat#7]
![image](https://user-images.githubusercontent.com/7859283/40017580-7748adca-57c2-11e8-9f0b-d05694fbec1d.png)

**Comment by tomekvenits** [comment]
Hi, can you give me more details when this error occurs?
Also snippet of your code will be very helpful ;)
Thanks.

**Comment by amiadsoto** [comment]
Yeah. First error "LC_Invite is not defined" is thrown on loading.
The rest happens during computer idle. We run a software company and can't have any exceptions in production.

2 files attached:
[Archive.zip](https://github.com/livechat/react-livechat/files/2003565/Archive.zip)

**Comment by tomekvenits** [comment]
Hi,
the problem is that `LC_Invite` is still being loaded when `onChatLoaded` is called.
Here is what you can do to ensure that `LC_Invite` will be loaded when you  call your methods:

*Based on code you sent me.*
```js
initChat = (ref) => {
 ref.on_after_load = function ()  {
    chatStore.updateRef(ref);
    chatStore.setVisitorName(user.fullName);
    chatStore.setVisitorEmail(user.email);
    chatStore.setAccountId(user.accountId);
    chatStore.setUserId(user._id);
    chatStore.checkActiveConversationOrHide();
  }		
}
```
Please let me know if that worked for you ;)

**Comment by amiadsoto** [comment]
Hey Venits,
That worked! Thanks!

Now we are still getting TypeError exception:
![image](https://user-images.githubusercontent.com/7859283/40047587-8d9f8884-5838-11e8-8e1d-805ccf9302b0.png)

Most likely due to lost connection (when I step away from my laptop and come back):
![image](https://user-images.githubusercontent.com/7859283/40047621-9fb688ce-5838-11e8-9856-39d5ebf7276b.png)

I use a macbook pro 2017 15"

**Comment by amiadsoto** [comment]
Hey @venits - did you happen to check the above error too?

**Comment by tomekvenits** [comment]
Hmm, I think you can get things like name, only after user fills up `start chat form`. I think you can use callback `onChatStarted ` and then call those methods.

**Comment by amiadsoto** [comment]
I didn't trigger this exception.
As I mentioned it was in the console after waking up the computer from sleep mode during an active chat.
No calls were made to 'name' or anything of that sort.

**Comment by AJ6546** [comment]
Hello I have the same Issue. 
Where should I add this code:

initChat = (ref) => {
 ref.on_after_load = function ()  {
    chatStore.updateRef(ref);
    chatStore.setVisitorName(user.fullName);
    chatStore.setVisitorEmail(user.email);
    chatStore.setAccountId(user.accountId);
    chatStore.setUserId(user._id);
    chatStore.checkActiveConversationOrHide();
  }		
}

**Comment by vzaidman** [comment]
I still have it. Please fix it!
