### ISSUE TITLE
Cannot resolve prop-types in react-livechat

### ISSUE THREAD

**Issue by chenghw** [livechat/react-livechat#8]
Hi, I'm currently having build issues with react-livechat in the following environments for `1.0.22`:

```
Node: 8.9.4
NPM: 6.0.1
```

Getting the error `Cannot resolve prop-types in react-livechat`. I'm think this may be an issue that the `package.json` is missing the `prop-types` package as a dependency?

**Comment by tomekvenits** [comment]
Hi,
I added `prop-types` to dependencies in version `1.0.24`.

This should solve your problem ;)

**Comment by chenghw** [comment]
Thanks!! 👍
